# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [385]:
# Install pandas and numpy if the active Python environment does not have them. Using Python venv is recommended when you are doing so.
%pip install pandas numpy

Requirement already satisfied: pandas in /usr/local/python/3.14.2/lib/python3.14/site-packages (3.0.6)
Requirement already satisfied: numpy in /usr/local/python/3.14.2/lib/python3.14/site-packages (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [386]:
# Import here.
import numpy as py
import pandas as pd

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

Load the Food choices data set into a new variable, `df_food`.

In [387]:
# Load the Food choices data set.

food_data_set_path = '../data/food_coded.csv'

df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [388]:
# Count by hand. (lol kidding)
df_food.shape

(125, 61)

In [389]:
# Try to print or display it nicely.
print("Rows: ", df_food.shape[0])
print("Columns: ", df_food.shape[1])

Rows:  125
Columns:  61

What are the columns and their types in this data set?

In [390]:
# Show the column names and their types.
df_food.dtypes

GPA                                 str
Gender                            int64
breakfast                         int64
calories_chicken                  int64
calories_day                    float64
calories_scone                  float64
coffee                            int64
comfort_food                        str
comfort_food_reasons                str
comfort_food_reasons_coded      float64
cook                            float64
comfort_food_reasons_coded.1      int64
cuisine                         float64
diet_current                        str
diet_current_coded                int64
drink                           float64
eating_changes                      str
eating_changes_coded              int64
eating_changes_coded1             int64
eating_out                        int64
employment                      float64
ethnic_food                       int64
exercise                        float64
father_education                float64
father_profession                   str
fav_cuisine                         str
fav_cuisine_coded                 int64
fav_food                        float64
food_childhood                      str
fries                             int64
fruit_day                         int64
grade_level                       int64
greek_food                        int64
healthy_feeling                   int64
healthy_meal                        str
ideal_diet                          str
ideal_diet_coded                  int64
income                          float64
indian_food                       int64
italian_food                      int64
life_rewarding                  float64
marital_status                  float64
meals_dinner_friend                 str
mother_education                float64
mother_profession                   str
nutritional_check                 int64
on_off_campus                   float64
parents_cook                      int64
pay_meal_out                      int64
persian_food                    float64
self_perception_weight          float64
soup                            float64
sports                          float64
thai_food                         int64
tortilla_calories               float64
turkey_calories                   int64
type_sports                         str
veggies_day                       int64
vitamins                          int64
waffle_calories                   int64
weight                              str
dtype: object

In [391]:
pd.set_option("display.max_rows", 100) # Set pandas to render up to 100 rows first. Default caps to 10 and takes the middle chunk out to make the DataFrame fit.

# Try to display the column information as a nice pandas DataFrame.
df_food.info()

<class 'pandas.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           123 non-null    str
 1   Gender                        125 non-null    int64
 2   breakfast                     125 non-null    int64
 3   calories_chicken              125 non-null    int64
 4   calories_day                  106 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64
 7   comfort_food                  124 non-null    str
 8   comfort_food_reasons          123 non-null    str
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64
 12  cuisine                       108 non-null    float64
 13  diet_current                  124 non-null    str
 14  diet_current_coded            125 non-null    int64
 15  drink                         123 non-null    float64
 16  eating_changes                122 non-null    str
 17  eating_changes_coded          125 non-null    int64
 18  eating_changes_coded1         125 non-null    int64
 19  eating_out                    125 non-null    int64
 20  employment                    116 non-null    float64
 21  ethnic_food                   125 non-null    int64
 22  exercise                      112 non-null    float64
 23  father_education              124 non-null    float64
 24  father_profession             122 non-null    str
 25  fav_cuisine                   123 non-null    str
 26  fav_cuisine_coded             125 non-null    int64
 27  fav_food                      123 non-null    float64
 28  food_childhood                124 non-null    str
 29  fries                         125 non-null    int64
 30  fruit_day                     125 non-null    int64
 31  grade_level                   125 non-null    int64
 32  greek_food                    125 non-null    int64
 33  healthy_feeling               125 non-null    int64
 34  healthy_meal                  124 non-null    str
 35  ideal_diet                    124 non-null    str
 36  ideal_diet_coded              125 non-null    int64
 37  income                        124 non-null    float64
 38  indian_food                   125 non-null    int64
 39  italian_food                  125 non-null    int64
 40  life_rewarding                124 non-null    float64
 41  marital_status                124 non-null    float64
 42  meals_dinner_friend           122 non-null    str
 43  mother_education              122 non-null    float64
 44  mother_profession             123 non-null    str
 45  nutritional_check             125 non-null    int64
 46  on_off_campus                 124 non-null    float64
 47  parents_cook                  125 non-null    int64
 48  pay_meal_out                  125 non-null    int64
 49  persian_food                  124 non-null    float64
 50  self_perception_weight        124 non-null    float64
 51  soup                          124 non-null    float64
 52  sports                        123 non-null    float64
 53  thai_food                     125 non-null    int64
 54  tortilla_calories             124 non-null    float64
 55  turkey_calories               125 non-null    int64
 56  type_sports                   99 non-null     str
 57  veggies_day                   125 non-null    int64
 58  vitamins                      125 non-null    int64
 59  waffle_calories               125 non-null    int64
 60  weight                        123 non-null    str
dtypes: float64(20), int64(27), str(14)
memory usage: 59.7 KB

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns? (Assign the result to a new variable, `df_food_col_subset`.)

In [392]:
# Remove ‘em.
df_food_col_subset=df_food[['calories_day','Gender','weight']].copy()
df_food_col_subset.head()

   calories_day  Gender                    weight
0           NaN       2                       187
1           3.0       1                       155
2           4.0       1  I'm not answering this.
3           3.0       1             Not sure, 240
4           2.0       1                       190

In [393]:
# Is there a second way to remove columns?
to_remove=df_food[['calories_day','Gender','weight']]
df_food=df_food.drop(columns=['calories_day','Gender','weight'])

In [394]:
# 🚀 Extra credit: What about a third way to remove columns?

#.pop for singular columns
#remove_column=df_food.pop('df_food_col_subset')

What about `NaN`s? How many are there?

In [395]:
# Count ‘em.
df_food.dtypes
df_food.isnull().sum()

GPA                              2
breakfast                        0
calories_chicken                 0
calories_scone                   1
coffee                           0
comfort_food                     1
comfort_food_reasons             2
comfort_food_reasons_coded      19
cook                             3
comfort_food_reasons_coded.1     0
cuisine                         17
diet_current                     1
diet_current_coded               0
drink                            2
eating_changes                   3
eating_changes_coded             0
eating_changes_coded1            0
eating_out                       0
employment                       9
ethnic_food                      0
exercise                        13
father_education                 1
father_profession                3
fav_cuisine                      2
fav_cuisine_coded                0
fav_food                         2
food_childhood                   1
fries                            0
fruit_day                        0
grade_level                      0
greek_food                       0
healthy_feeling                  0
healthy_meal                     1
ideal_diet                       1
ideal_diet_coded                 0
income                           1
indian_food                      0
italian_food                     0
life_rewarding                   1
marital_status                   1
meals_dinner_friend              3
mother_education                 3
mother_profession                2
nutritional_check                0
on_off_campus                    1
parents_cook                     0
pay_meal_out                     0
persian_food                     1
self_perception_weight           1
soup                             1
sports                           2
thai_food                        0
tortilla_calories                1
turkey_calories                  0
type_sports                     26
veggies_day                      0
vitamins                         0
waffle_calories                  0
dtype: int64

In [396]:
# 🚀 Extra credit: Try to display the NaN sums as a nice pandas DataFrame.

In [397]:
# 🚀 Extra credit: You can turn one line of code into multiple lines of code using a backslash as a continuation character to break up what would otherwise be a long line.

We gotta remove those `NaN`s―the entire row.

In [398]:
# Drop ‘em in-place.
df_dropped=df_food.dropna()
df_food.dropna(inplace=True)
df_food.isnull().sum()

GPA                             0
breakfast                       0
calories_chicken                0
calories_scone                  0
coffee                          0
comfort_food                    0
comfort_food_reasons            0
comfort_food_reasons_coded      0
cook                            0
comfort_food_reasons_coded.1    0
cuisine                         0
diet_current                    0
diet_current_coded              0
drink                           0
eating_changes                  0
eating_changes_coded            0
eating_changes_coded1           0
eating_out                      0
employment                      0
ethnic_food                     0
exercise                        0
father_education                0
father_profession               0
fav_cuisine                     0
fav_cuisine_coded               0
fav_food                        0
food_childhood                  0
fries                           0
fruit_day                       0
grade_level                     0
greek_food                      0
healthy_feeling                 0
healthy_meal                    0
ideal_diet                      0
ideal_diet_coded                0
income                          0
indian_food                     0
italian_food                    0
life_rewarding                  0
marital_status                  0
meals_dinner_friend             0
mother_education                0
mother_profession               0
nutritional_check               0
on_off_campus                   0
parents_cook                    0
pay_meal_out                    0
persian_food                    0
self_perception_weight          0
soup                            0
sports                          0
thai_food                       0
tortilla_calories               0
turkey_calories                 0
type_sports                     0
veggies_day                     0
vitamins                        0
waffle_calories                 0
dtype: int64

In [399]:
# 🚀 Extra credit: Check if the in-place modifications also affected the original DataFrame, df_food. 🙂

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [400]:
# Fix that in-place.
df_food_col_subset['weight'].dtype
df_food_col_subset['weight'] = pd.to_numeric(df_food_col_subset['weight'], errors='coerce')
df_food_col_subset['weight_fixed'] = df_food_col_subset['weight'].fillna(df_food_col_subset['weight'].mean())
df_food_col_subset

     calories_day  Gender  weight  weight_fixed
0             NaN       2   187.0         187.0
1             3.0       1   155.0         155.0
2             4.0       1     NaN         158.5
3             3.0       1     NaN         158.5
4             2.0       1   190.0         190.0
..            ...     ...     ...           ...
120           4.0       1   156.0         156.0
121           2.0       1   180.0         180.0
122           NaN       1   120.0         120.0
123           4.0       2   135.0         135.0
124           NaN       1   135.0         135.0

[125 rows x 4 columns]

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [401]:
# Savey save!
df_food_col_subset.to_csv('../data/food_coded_cleaned.csv', index=False)

In [402]:
# 🚀 Extra credit: Load and print a few lines of the saved file as plain text.

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

Load the Ask A Manager Salary Survey 2021 (Responses) data set into a new variable, `df_salary`.

In [403]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set.
salary_data_set_path = '../data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv'
df_salary = pd.read_csv(salary_data_set_path, sep='\t')

Was that hard? 🙃

### Explore

You know the drill.

How much data did you just load?

In [404]:
# Count by hand. I’m dead serious.
df_salary.shape

(28062, 18)

What are the columns and their types?

In [405]:
# Show the column names and their types.
df_salary.dtypes

Timestamp                                                                                                                                                                                                                                   str
How old are you?                                                                                                                                                                                                                            str
What industry do you work in?                                                                                                                                                                                                               str
Job title                                                                                                                                                                                                                                   str
If your job title needs additional context, please clarify here:                                                                                                                                                                            str
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)        str
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                          float64
Please indicate the currency                                                                                                                                                                                                                str
If "Other," please indicate the currency here:                                                                                                                                                                                              str
If your income needs additional context, please provide it here:                                                                                                                                                                            str
What country do you work in?                                                                                                                                                                                                                str
If you're in the U.S., what state do you work in?                                                                                                                                                                                           str
What city do you work in?                                                                                                                                                                                                                   str
How many years of professional work experience do you have overall?                                                                                                                                                                         str
How many years of professional work experience do you have in your field?                                                                                                                                                                   str
What is your highest level of education completed?                                                                                                                                                                                          str
What is your gender?                                                                                                                                                                                                                        str
What is your race? (Choose all that apply.)                                                                                                                                                                                                 str
dtype: object

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [406]:
# Rename ‘em in-place.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed	gender, race
df_salary.columns = [
    'timestamp', 'age', 'industry', 'title', 'title_context', 'salary','additional_compensation', 'currency', 'other_currency',
    'salary_context','country', 'state', 'city', 'total_yoe', 'field_yoe','highest_education_completed', 'gender', 'race'
]
df_salary

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28057,7/12/2024 22:52:01,35-44,Health care,Veterinarian,NaN,135000,NaN,USD,NaN,NaN,United States,Missouri,Wentzville,11 - 20 years,11 - 20 years,"Professional degree (MD, JD, etc.)",Woman,White
28058,7/23/2024 17:51:03,25-34,Computing or Tech,Systems Architect,NaN,109000,NaN,USD,NaN,NaN,USA,Georgia,Atlanta,5-7 years,5-7 years,College degree,Man,White
28059,7/24/2024 12:22:58,18-24,"Accounting, Banking & Finance",Risk Management Associate,NaN,1200,0.0,USD,NaN,NaN,Myanmar,Colorado,Yangon,2 - 4 years,2 - 4 years,Some college,Man,Asian or Asian American
28060,7/26/2024 11:20:45,18-24,Computing or Tech,IT,NaN,1700,10.0,USD,NaN,NaN,Burma,NaN,Yangon,2 - 4 years,1 year or less,Some college,Man,Asian or Asian American
28061,8/20/2024 1:06:13,25-34,Health care,Clinical physiologist,NaN,1200000,NaN,Other,NGN,NaN,Nigeria,NaN,Lagos,2 - 4 years,2 - 4 years,College degree,Woman,Black or African American

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [407]:
# List the unique industries and a count of their instances.
df_salary['industry'].value_counts()

industry
Computing or Tech                               4699
Education (Higher Education)                    2464
Nonprofits                                      2419
Health care                                     1896
Government and Public Administration            1889
                                                ...
Undergrad student                                  1
Concrete Construction                              1
I'm currently a student and don't have a job       1
Student                                            1
Wine & Spirits                                     1
Name: count, Length: 1219, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new variable, `df_salary_tech`.

In [408]:
# Filtery filter.

# compares rows, keeps same ones
df_salary_tech = df_salary[df_salary['industry'] == 'Computing or Tech']

Do a sanity check by counting.

In [409]:
# Sanity check count.
len(df_salary_tech)

4699

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [410]:
# Filtery filter (in place) for just the jobs that pay in USD!
df_salary_tech = df_salary_tech[df_salary_tech['currency'] == 'USD']
#only Usd currency remains

What we really want know is how each U.S. state pays in tech. What value in `country` represents the United States of America?

In [411]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.
df_salary_tech['country'].value_counts()

country
United States                1576
USA                          1222
US                            412
U.S.                          108
United States of America       90
United States                  68
Usa                            59
USA                            56
usa                            28
United states                  23
united states                  14
Us                             12
us                              9
U.S.A.                          7
United States of America        7
Israel                          5
Canada                          4
U.S.                            2
United State of America         2
Unite States                    2
Australia                       2
UnitedStates                    2
India                           2
U.S                             2
Usa                             2
United States Of America        2
Spain                           2
Brazil                          2
United Kingdom                  2
united States                   2
New Zealand                     2
Poland                          2
France                          2
U.S.A                           2
United States of america        2
US                              1
Uniyed states                   1
America                         1
Puerto Rico                     1
U.s.                            1
 US                             1
United State                    1
Cuba                            1
Danmark                         1
Italy                           1
International                   1
United Stated                   1
Remote (philippines)            1
Singapore                       1
Uruguay                         1
Mexico                          1
Canada                          1
United Stateds                  1
ISA                             1
singapore                       1
Pakistan                        1
Netherlands                     1
China                           1
San Francisco                   1
Romania                         1
United STates                   1
Japan                           1
United Stares                   1
Australian                      1
Denmark                         1
Jamaica                         1
Unites States                   1
Thailand                        1
U.S.A                           1
Colombia                        1
denmark                         1
Ghana                           1
Nigeria                         1
ss                              1
Nigeria                         1
Burma                           1
Name: count, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [412]:
# Replace them all in-place with 'US'.
#
df_salary_tech['country'] = df_salary_tech['country'].replace(
    ['US', 'USA', 'United States', 'U.S.', 'usa'],
    'US'
)

Have a look at the count of each unique country again now.

In [413]:
# Count again.
df_salary_tech['country'].value_counts()

country
US                           3346
United States of America       90
United States                  68
Usa                            59
USA                            56
United states                  23
united states                  14
Us                             12
us                              9
U.S.A.                          7
United States of America        7
Israel                          5
Canada                          4
U.S.                            2
United State of America         2
Unite States                    2
Australia                       2
UnitedStates                    2
India                           2
U.S                             2
Usa                             2
United States Of America        2
Spain                           2
Brazil                          2
United Kingdom                  2
united States                   2
New Zealand                     2
Poland                          2
France                          2
U.S.A                           2
United States of america        2
US                              1
Uniyed states                   1
America                         1
Puerto Rico                     1
U.s.                            1
 US                             1
United State                    1
Cuba                            1
Danmark                         1
Italy                           1
International                   1
United Stated                   1
Remote (philippines)            1
Singapore                       1
Uruguay                         1
Mexico                          1
Canada                          1
United Stateds                  1
ISA                             1
singapore                       1
Pakistan                        1
Netherlands                     1
China                           1
San Francisco                   1
Romania                         1
United STates                   1
Japan                           1
United Stares                   1
Australian                      1
Denmark                         1
Jamaica                         1
Unites States                   1
Thailand                        1
U.S.A                           1
Colombia                        1
denmark                         1
Ghana                           1
Nigeria                         1
ss                              1
Nigeria                         1
Burma                           1
Name: count, dtype: int64

Did you notice anything interesting?

In [414]:
# 🚀 Extra credit: Resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.

In [415]:

# 🚀 Extra credit: If you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [416]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.
df_salary_tech.groupby('state')['salary'].agg(['min', 'mean', 'max']).sort_values('mean', ascending=False)
#groups by state and salary the uses .agg to use one operation among them all, puts into mean coumn, in desc3nding

TypeError: dtype 'str' does not support operation 'mean'

 Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed. 🤔

In [ ]:
# Fix it in-place.
df_salary_tech['salary'] = pd.to_numeric(df_salary_tech['salary'], errors='coerce')

Let’s try that again.

In [ ]:
# Try it again. Yeah!
df_salary_tech.groupby('state')['salary'].agg(['min', 'mean', 'max']).sort_values('mean', ascending=False)
#groups by state and salary the uses .agg to use one operation among them all, puts into mean coumn, in desc3nding

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [ ]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.
df_salary_tech['timestamp'] = pd.to_datetime(df_salary_tech['timestamp'], errors='coerce')

df_salary_recent = df_salary_tech[df_salary_tech['timestamp'].dt.year.isin([2021, 2022, 2023])]

#time stamp to real date type then filter 2021-2022 inside out

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)